name: Native

on: [ push, workflow_dispatch ]

env:
  CC: clang
  CXX: clang++
  BUILD_TYPE: Debug
  PROJECT_SUBDIR: sgbmandroid/src/main/cpp
  BUILD_SUBDIR: build

defaults:
  run:
    working-directory: sgbmandroid/src/main/cpp  # Must be the same as env.PROJECT_SUBDIR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hendrikmuhs/ccache-action@v1.2

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/${{env.PROJECT_SUBDIR}}/${{env.BUILD_SUBDIR}}
          key: ${{runner.os}}-build-cache

      - name: Cache compile commands
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/${{env.PROJECT_SUBDIR}}/${{env.BUILD_SUBDIR}}/compile_commands.json
          key: ${{runner.os}}-compile-commands

      - name: Configure CMake
        run: |
          sudo apt-get install ninja-build  # Ninja is used as the tool from Android's NDK
          cmake -G Ninja -B ${{env.BUILD_SUBDIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build ${{env.BUILD_SUBDIR}} --config ${{env.BUILD_TYPE}}

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/${{env.PROJECT_SUBDIR}}/${{env.BUILD_SUBDIR}}/compile_commands.json
          key: ${{runner.os}}-compile-commands

      - name: Configure linters
        run: |
          pip install cpplint
          sudo apt-get install clang-tidy

      - name: Run cpplint
        run: cpplint --recursive .

      - name: Run clang-tidy
        run: run-clang-tidy -p ${{env.BUILD_SUBDIR}}
