name: Native

on: [ push, workflow_dispatch ]

env:
  CC: clang
  CXX: clang++
  BUILD_TYPE: Debug
  PROJECT_SUBDIR: lib/src/main/cpp
  BUILD_SUBDIR: build
  CCACHE_DIR: ${{github.workspace}}/.cache/ccache

defaults:
  run:
    working-directory: lib/src/main/cpp  # Must be the same as env.PROJECT_SUBDIR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}/${{env.PROJECT_SUBDIR}}/${{env.BUILD_SUBDIR}}
            ${{env.CCACHE_DIR}}
          key: ${{runner.os}}-build-cache

      - name: Configure ccache
        run: sudo apt-get install ccache

      - name: Configure CMake
        run: |
          sudo apt-get install ninja-build
          cmake -G Ninja -B ${{env.BUILD_SUBDIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build ${{env.BUILD_SUBDIR}} --config ${{env.BUILD_TYPE}}

      - name: Print ccache stats
        run: ccache -s

      - name: Configure linters
        run: |
          pip install cpplint
          sudo apt-get install clang-tidy

      - name: Run cpplint
        run: cpplint --recursive .

      - name: Run clang-tidy
        run: run-clang-tidy -p ${{env.BUILD_SUBDIR}}
